<?php

namespace SoccerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SoccerBundle\Entity\Game;
use SoccerBundle\Entity\Team;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{


    public function getAllGamesByTeam(Team $team)
    {
        $qb = $this->createQueryBuilder('g');
        $qb->Where('g.homeTeam = :team')
            ->orWhere('g.awayTeam = :team')
            ->setParameter('team', $team)
            ->orderBy('g.date','desc');

        $query = $qb->getQuery();

        return $query->execute();
    }

    public function getAllGames()
    {
        $qb = $this->createQueryBuilder('g');
        $qb->orderBy('g.date','desc');

        $query = $qb->getQuery();

        return $query->execute();
    }
}
